import type { AppProps } from "next/app";
import Head from "next/head";
import { GlobalStyles } from "../styles/globals";

function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>React avançado - Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
      <GlobalStyles />
    </>
  );
}
export default App;
